[package]
name = "svg-gen"
version = "0.1.0"
authors = ["Vaughn Kottler <vaughnkottler@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
yaml-rust = "0.4"
