{% set body_width = (canvas.height * 2) / 3 %}
pin:
  color: "#263238"
  spacing: {{body_width / (pin.count + 1)}}
  count: {{pin.count}}
  height: {{body_width / (pin.count * 2)}}
  width: {{(body_width / (pin.count * 2)) * 2.4}}
  radius: {{(body_width / (pin.count * 2)) / 2}}
body:
  side: {{body_width}}
  fill: "black"
symbol:
  stroke: {{body_width / 20}}
  color: "white"
canvas:
  width: {{canvas.width}}
  height: {{canvas.height}}
