pin:
  color: "#263238"
  height: {{body.side / (pin.count * 2)}}
  width: {{(body.side / (pin.count * 2)) * 2.4}}
  radius: {{(body.side / (pin.count * 2)) / 2}}
body:
  side: {{body.side}}
symbol:
  stroke: {{body.side / 20}}
