size: {{size|default(global.svg.height, true)}}
x_offset: {{x_offset|default(0, true)}}
y_offset: {{y_offset|default(0, true)}}
pin:
  count: {{pin.count|default(4, true)}}
  color: {{pin.color|default('"#263238"', true)}}
body:
  color: {{body.color|default('"black"', true)}}
background:
  color: {{background.color|default('"#607d8b"', true)}}
