background:
  color:
    theme: {{theme}}
    variant: primary
    hue: 800
symbol:
  color:
    theme: {{theme}}
    variant: primary
    hue: 50
  color2:
    theme: {{theme}}
    variant: primary
    hue: 900
