# TODO - this is all just copied
background:
  color:
    theme: {{theme}}
    variant: primary
    hue: 500
symbol:
  color:
    theme: {{theme}}
    variant: primary
    hue: 50
  color2:
    theme: {{theme}}
    variant: primary
    hue: 100
