size: {{size}}
pin:
  count: {{pin.count|default(4, true)}}
  color:
    theme: {{theme}}
    variant: primary
    hue: 800
body:
  color:
    theme: gray
    variant: primary
    hue: 800
background:
  color:
    theme: {{theme}}
    variant: primary
    hue: 500
symbol:
  color:
    theme: {{theme}}
    variant: primary
    hue: 50
  color2:
    theme: {{theme}}
    variant: primary
    hue: 100
