size: {{size}}
pin:
  count: {{pin.count|default(4, true)}}
  color: "{{pin.color|default(global.color.blue_gray.primary.800, true)}}"
body:
  color: "{{body.color|default(global.color.gray.primary.800, true)}}"
background:
  color: "{{background.color|default(global.color.blue_gray.primary.500, true)}}"
symbol:
  color: "{{symbol.color|default(global.color.blue_gray.primary.50, true)}}"
  color2: "{{symbol.color2|default(global.color.blue_gray.primary.100, true)}}"
