size: {{size}}
pin:
  count: {{pin.count|default(4, true)}}
  color:
    theme: {{pin.theme|default("blue_gray", true)}}
    variant: primary
    hue: {{pin.hue|default(800, true)}}
body:
  color:
    theme: {{body.theme|default("gray", true)}}
    variant: primary
    hue: {{body.hue|default(800, true)}}
